### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tatsuya-ogi312** [tatsuya-ogi312/furima-38499#21]
# URL
https://furima-38499.herokuapp.com/
# Basic認証
ユーザー：techchamp
PASS：8281
# User1 info
mail-address:admin@user
password:admin1
# User2 info
mail-address:tanuki@user
password:admin2
# Other
ご対応よろしくお願いします。

**Comment by snkw-works** [comment]
@tatsuya-ogi312 さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されるよう修正しましょう**
「ベビー・キッズ」が正しく表示されていない状態です。
<img width="624" alt="スクリーンショット_2022-10-04_17_46_40" src="https://user-images.githubusercontent.com/54050089/193776340-4916f50f-047c-4d70-943f-89b432c056ad.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by tatsuya-ogi312** [comment]
# URL
https://furima-38499.herokuapp.com/
# Basic認証
ユーザー：techchamp
PASS：8281
# User1 info
mail-address:admin@user
password:admin1
# User2 info
mail-address:tanuki@user
password:admin2
# Other
修正しましたので、ご確認お願いします！

**Comment by snkw-works** [comment]
@tatsuya-ogi312 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

`本メッセージ内で、今後の学習についてご案内しています。必ず確認するようにしてください。`

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

------------------------------------------------------------------------------------------
◆ 今後の流れについてのご案内（※詳細は下記リンクのガイダンス資料参照）
------------------------------------------------------------------------------------------
◎この後の期間では、以下のアクションが必要となります。
・最終課題説明文の作成・提出
・FURIMAへの追加機能の実装 または オリジナルアプリ開発
・上記の開発に関する要件定義書の提出
・履歴書と職務経歴書の作成・提出（転職サポートありの方）
・学習成果発表会の準備

◎下記リンク先の「**追加実装・オリジナルアプリ開発 ガイダンス資料**」を必ずご確認ください。
**https://master.tech-camp.in/v2/curriculums/7839**

------------------------------------------------------------------------------------------
◆ さいごに
------------------------------------------------------------------------------------------
◎ガイダンス資料を確認した上で、今後の流れについて不明点がございましたら、担当ライフコーチまでご相談ください。

◎いよいよ卒業までのラストスパートです。これまで頑張ってきたことをフル活用して、最大限の受講成果につなげていきましょう。

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by tatsuya-ogi312** [comment]
ご確認いただきありがとうございました！
引き続き卒業に向けて頑張ります！
